/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package iot.state;
@org.apache.avro.specific.AvroGenerated
public enum Device implements org.apache.avro.generic.GenericEnumSymbol<Device> {
  PIR, CAMERA, SIREN, LIGHT, TEMPERATURE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Device\",\"namespace\":\"iot.state\",\"symbols\":[\"PIR\",\"CAMERA\",\"SIREN\",\"LIGHT\",\"TEMPERATURE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
