/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package iot.trigger;
@org.apache.avro.specific.AvroGenerated
public enum Operator implements org.apache.avro.generic.GenericEnumSymbol<Operator> {
  GREAT, LESS, EQUAL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Operator\",\"namespace\":\"iot.trigger\",\"symbols\":[\"GREAT\",\"LESS\",\"EQUAL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
