/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package iot.trigger;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Trigger extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4223112417532818055L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Trigger\",\"namespace\":\"iot.trigger\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"state\",\"type\":\"int\"},{\"name\":\"timestamp\",\"type\":\"int\"},{\"name\":\"value\",\"type\":\"int\"},{\"name\":\"operator\",\"type\":{\"type\":\"enum\",\"name\":\"Operator\",\"symbols\":[\"GREAT\",\"LESS\",\"EQUAL\"]}},{\"name\":\"device\",\"type\":{\"type\":\"enum\",\"name\":\"Device\",\"symbols\":[\"PIR\",\"CAMERA\",\"SIREN\",\"LIGHT\",\"TEMPERATURE\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Trigger> ENCODER =
      new BinaryMessageEncoder<Trigger>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Trigger> DECODER =
      new BinaryMessageDecoder<Trigger>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Trigger> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Trigger> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Trigger> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Trigger>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Trigger to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Trigger from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Trigger instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Trigger fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence id;
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public int state;
  @Deprecated public int timestamp;
  @Deprecated public int value;
  @Deprecated public iot.trigger.Operator operator;
  @Deprecated public iot.trigger.Device device;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Trigger() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param name The new value for name
   * @param state The new value for state
   * @param timestamp The new value for timestamp
   * @param value The new value for value
   * @param operator The new value for operator
   * @param device The new value for device
   */
  public Trigger(java.lang.CharSequence id, java.lang.CharSequence name, java.lang.Integer state, java.lang.Integer timestamp, java.lang.Integer value, iot.trigger.Operator operator, iot.trigger.Device device) {
    this.id = id;
    this.name = name;
    this.state = state;
    this.timestamp = timestamp;
    this.value = value;
    this.operator = operator;
    this.device = device;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return state;
    case 3: return timestamp;
    case 4: return value;
    case 5: return operator;
    case 6: return device;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: name = (java.lang.CharSequence)value$; break;
    case 2: state = (java.lang.Integer)value$; break;
    case 3: timestamp = (java.lang.Integer)value$; break;
    case 4: value = (java.lang.Integer)value$; break;
    case 5: operator = (iot.trigger.Operator)value$; break;
    case 6: device = (iot.trigger.Device)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'state' field.
   * @return The value of the 'state' field.
   */
  public int getState() {
    return state;
  }


  /**
   * Sets the value of the 'state' field.
   * @param value the value to set.
   */
  public void setState(int value) {
    this.state = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public int getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(int value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'value' field.
   * @return The value of the 'value' field.
   */
  public int getValue() {
    return value;
  }


  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(int value) {
    this.value = value;
  }

  /**
   * Gets the value of the 'operator' field.
   * @return The value of the 'operator' field.
   */
  public iot.trigger.Operator getOperator() {
    return operator;
  }


  /**
   * Sets the value of the 'operator' field.
   * @param value the value to set.
   */
  public void setOperator(iot.trigger.Operator value) {
    this.operator = value;
  }

  /**
   * Gets the value of the 'device' field.
   * @return The value of the 'device' field.
   */
  public iot.trigger.Device getDevice() {
    return device;
  }


  /**
   * Sets the value of the 'device' field.
   * @param value the value to set.
   */
  public void setDevice(iot.trigger.Device value) {
    this.device = value;
  }

  /**
   * Creates a new Trigger RecordBuilder.
   * @return A new Trigger RecordBuilder
   */
  public static iot.trigger.Trigger.Builder newBuilder() {
    return new iot.trigger.Trigger.Builder();
  }

  /**
   * Creates a new Trigger RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Trigger RecordBuilder
   */
  public static iot.trigger.Trigger.Builder newBuilder(iot.trigger.Trigger.Builder other) {
    if (other == null) {
      return new iot.trigger.Trigger.Builder();
    } else {
      return new iot.trigger.Trigger.Builder(other);
    }
  }

  /**
   * Creates a new Trigger RecordBuilder by copying an existing Trigger instance.
   * @param other The existing instance to copy.
   * @return A new Trigger RecordBuilder
   */
  public static iot.trigger.Trigger.Builder newBuilder(iot.trigger.Trigger other) {
    if (other == null) {
      return new iot.trigger.Trigger.Builder();
    } else {
      return new iot.trigger.Trigger.Builder(other);
    }
  }

  /**
   * RecordBuilder for Trigger instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Trigger>
    implements org.apache.avro.data.RecordBuilder<Trigger> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence name;
    private int state;
    private int timestamp;
    private int value;
    private iot.trigger.Operator operator;
    private iot.trigger.Device device;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(iot.trigger.Trigger.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.state)) {
        this.state = data().deepCopy(fields()[2].schema(), other.state);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[3].schema(), other.timestamp);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.value)) {
        this.value = data().deepCopy(fields()[4].schema(), other.value);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.operator)) {
        this.operator = data().deepCopy(fields()[5].schema(), other.operator);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.device)) {
        this.device = data().deepCopy(fields()[6].schema(), other.device);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing Trigger instance
     * @param other The existing instance to copy.
     */
    private Builder(iot.trigger.Trigger other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.state)) {
        this.state = data().deepCopy(fields()[2].schema(), other.state);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[3].schema(), other.timestamp);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.value)) {
        this.value = data().deepCopy(fields()[4].schema(), other.value);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.operator)) {
        this.operator = data().deepCopy(fields()[5].schema(), other.operator);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.device)) {
        this.device = data().deepCopy(fields()[6].schema(), other.device);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public iot.trigger.Trigger.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public iot.trigger.Trigger.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public iot.trigger.Trigger.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public iot.trigger.Trigger.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'state' field.
      * @return The value.
      */
    public int getState() {
      return state;
    }


    /**
      * Sets the value of the 'state' field.
      * @param value The value of 'state'.
      * @return This builder.
      */
    public iot.trigger.Trigger.Builder setState(int value) {
      validate(fields()[2], value);
      this.state = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'state' field has been set.
      * @return True if the 'state' field has been set, false otherwise.
      */
    public boolean hasState() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'state' field.
      * @return This builder.
      */
    public iot.trigger.Trigger.Builder clearState() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public int getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public iot.trigger.Trigger.Builder setTimestamp(int value) {
      validate(fields()[3], value);
      this.timestamp = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public iot.trigger.Trigger.Builder clearTimestamp() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'value' field.
      * @return The value.
      */
    public int getValue() {
      return value;
    }


    /**
      * Sets the value of the 'value' field.
      * @param value The value of 'value'.
      * @return This builder.
      */
    public iot.trigger.Trigger.Builder setValue(int value) {
      validate(fields()[4], value);
      this.value = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'value' field.
      * @return This builder.
      */
    public iot.trigger.Trigger.Builder clearValue() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'operator' field.
      * @return The value.
      */
    public iot.trigger.Operator getOperator() {
      return operator;
    }


    /**
      * Sets the value of the 'operator' field.
      * @param value The value of 'operator'.
      * @return This builder.
      */
    public iot.trigger.Trigger.Builder setOperator(iot.trigger.Operator value) {
      validate(fields()[5], value);
      this.operator = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'operator' field has been set.
      * @return True if the 'operator' field has been set, false otherwise.
      */
    public boolean hasOperator() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'operator' field.
      * @return This builder.
      */
    public iot.trigger.Trigger.Builder clearOperator() {
      operator = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'device' field.
      * @return The value.
      */
    public iot.trigger.Device getDevice() {
      return device;
    }


    /**
      * Sets the value of the 'device' field.
      * @param value The value of 'device'.
      * @return This builder.
      */
    public iot.trigger.Trigger.Builder setDevice(iot.trigger.Device value) {
      validate(fields()[6], value);
      this.device = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'device' field has been set.
      * @return True if the 'device' field has been set, false otherwise.
      */
    public boolean hasDevice() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'device' field.
      * @return This builder.
      */
    public iot.trigger.Trigger.Builder clearDevice() {
      device = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Trigger build() {
      try {
        Trigger record = new Trigger();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.state = fieldSetFlags()[2] ? this.state : (java.lang.Integer) defaultValue(fields()[2]);
        record.timestamp = fieldSetFlags()[3] ? this.timestamp : (java.lang.Integer) defaultValue(fields()[3]);
        record.value = fieldSetFlags()[4] ? this.value : (java.lang.Integer) defaultValue(fields()[4]);
        record.operator = fieldSetFlags()[5] ? this.operator : (iot.trigger.Operator) defaultValue(fields()[5]);
        record.device = fieldSetFlags()[6] ? this.device : (iot.trigger.Device) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Trigger>
    WRITER$ = (org.apache.avro.io.DatumWriter<Trigger>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Trigger>
    READER$ = (org.apache.avro.io.DatumReader<Trigger>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeString(this.name);

    out.writeInt(this.state);

    out.writeInt(this.timestamp);

    out.writeInt(this.value);

    out.writeEnum(this.operator.ordinal());

    out.writeEnum(this.device.ordinal());

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);

      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

      this.state = in.readInt();

      this.timestamp = in.readInt();

      this.value = in.readInt();

      this.operator = iot.trigger.Operator.values()[in.readEnum()];

      this.device = iot.trigger.Device.values()[in.readEnum()];

    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          break;

        case 1:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        case 2:
          this.state = in.readInt();
          break;

        case 3:
          this.timestamp = in.readInt();
          break;

        case 4:
          this.value = in.readInt();
          break;

        case 5:
          this.operator = iot.trigger.Operator.values()[in.readEnum()];
          break;

        case 6:
          this.device = iot.trigger.Device.values()[in.readEnum()];
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










